--CREATE DATABASE CustomerMSDB

--CREATE DATABASE DriverMSDB

--CREATE DATABASE RestaurantMSDB

--CREATE DATABASE OrderMSDB

USE CustomerMSDB;
CREATE TABLE Customer(
Id INT NOT NULL IDENTITY(1,1),
FirstName VARCHAR(100) NULL,
LastName VARCHAR(100) NOT NULL,
Email VARCHAR(256) NULL,
Mobile VARCHAR(15) NULL,
Address NVARCHAR(MAX) NULL
)
GO;

USE RestaurantMSDB
GO;
CREATE TABLE Menu(
Id INT NOT NULL IDENTITY(1,1),
FoodName VARCHAR(100) NULL,
Price INT NOT NULL,
Quantity INT NULL
)

CREATE TABLE Restaurant(
Id INT NOT NULL IDENTITY(1,1),
Name VARCHAR(100) NOT NULL,
Location NVARCHAR(MAX) NULL,
MenuId INT NULL
)
--ALTER TABLE Restaurant ADD MenuId INT
USE DriverMSDB
GO;
CREATE TABLE Driver(
Id INT NOT NULL IDENTITY(1,1),
FirstName VARCHAR(100) NULL,
LastName VARCHAR(100) NOT NULL,
Email VARCHAR(256) NULL,
Mobile VARCHAR(15) NULL
)

USE OrderMSDB
GO;
CREATE TABLE Orders(
Id INT NOT NULL IDENTITY(1,1),
OrderNumber INT NOT NULL,
RestaurantId INT not null,
RestaurantName VARCHAR(100) NULL,
CustomerId INT NOT NULL,
CustomerName VARCHAR(100) NULL,
DriverName VARCHAR(100) NULL,
DriverId INT,
Price INT NULL,
Quantity INT NULL,
OrderDate DATETIME NULL,
IsOrderDelivered BIT NULL
)
--drop table Orders
--ALTER TABLE Orders ADD DriverId INT 

--CREATE DATABASE UserMSDB
USE UserMSDB
GO;
CREATE TABLE [User](
Id INT NOT NULL IDENTITY(1,1),
FirstName VARCHAR(100) NULL,
LastName VARCHAR(100) NOT NULL,
Email VARCHAR(256) NULL,
Password VARCHAR(256) NULL,
UserRole VARCHAR(15) NOT NULL
)